### ISSUE TITLE
dkms module will not build on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by alkopit** [im-0/hpsahba#38]
make.log

> DKMS make.log for hpsa-dkms-1.0 for kernel 5.15.0-86-generic (x86_64)
> Wed Oct 18 02:17:36 PM UTC 2023
> make -C /usr/lib/modules/5.15.0-86-generic/build M=/var/lib/dkms/hpsa-dkms/1.0/build modules
> make[1]: Entering directory '/usr/src/linux-headers-5.15.0-86-generic'
>   CC [M]  /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.o
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:82:25: error: expected declaration specifiers or ‘...’ before string constant
>    82 | MODULE_SUPPORTED_DEVICE("HP Smart Array Controllers");
>       |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from ./include/linux/export.h:45,
>                  from ./include/linux/linkage.h:7,
>                  from ./include/linux/kernel.h:8,
>                  from ./include/linux/list.h:9,
>                  from ./include/linux/module.h:12,
>                  from /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:20:
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c: In function ‘hpsa_scsi_queue_command’:
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:5777:19: error: ‘struct scsi_cmnd’ has no member named ‘request’
>  5777 |         BUG_ON(cmd->request->tag < 0);
>       |                   ^~
> ./include/linux/compiler.h:78:45: note: in definition of macro ‘unlikely’
>    78 | # define unlikely(x)    __builtin_expect(!!(x), 0)
>       |                                             ^
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:5777:9: note: in expansion of macro ‘BUG_ON’
>  5777 |         BUG_ON(cmd->request->tag < 0);
>       |         ^~~~~~
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:5816:51: error: ‘struct scsi_cmnd’ has no member named ‘request’
>  5816 |                         !blk_rq_is_passthrough(cmd->request) &&
>       |                                                   ^~
> ./include/linux/compiler.h:77:45: note: in definition of macro ‘likely’
>    77 | # define likely(x)      __builtin_expect(!!(x), 1)
>       |                                             ^
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c: In function ‘hpsa_get_cmd_index’:
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:5980:23: error: ‘struct scsi_cmnd’ has no member named ‘request’
>  5980 |         int idx = scmd->request->tag;
>       |                       ^~
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c: In function ‘hpsa_scsi_ioaccel_raid_map’:
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:5247:26: warning: this statement may fall through [-Wimplicit-fallthrough=]
>  5247 |                 is_write = 1;
>       |                 ~~~~~~~~~^~~
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:5249:9: note: here
>  5249 |         case READ_6:
>       |         ^~~~
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:5258:26: warning: this statement may fall through [-Wimplicit-fallthrough=]
>  5258 |                 is_write = 1;
>       |                 ~~~~~~~~~^~~
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:5260:9: note: here
>  5260 |         case READ_10:
>       |         ^~~~
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:5271:26: warning: this statement may fall through [-Wimplicit-fallthrough=]
>  5271 |                 is_write = 1;
>       |                 ~~~~~~~~~^~~
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:5273:9: note: here
>  5273 |         case READ_12:
>       |         ^~~~
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:5286:26: warning: this statement may fall through [-Wimplicit-fallthrough=]
>  5286 |                 is_write = 1;
>       |                 ~~~~~~~~~^~~
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:5288:9: note: here
>  5288 |         case READ_16:
>       |         ^~~~
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c: In function ‘fixup_ioaccel_cdb’:
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:4797:26: warning: this statement may fall through [-Wimplicit-fallthrough=]
>  4797 |                 is_write = 1;
>       |                 ~~~~~~~~~^~~
> /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.c:4799:9: note: here
>  4799 |         case READ_6:
>       |         ^~~~
> make[2]: *** [scripts/Makefile.build:297: /var/lib/dkms/hpsa-dkms/1.0/build/hpsa.o] Error 1
> make[1]: *** [Makefile:1909: /var/lib/dkms/hpsa-dkms/1.0/build] Error 2
> make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-86-generic'
> make: *** [Makefile:14: default] Error 2

**Comment by alkopit** [comment]
sorry, problem selffixed...)

**Comment by alkopit** [comment]
p212
I successfully turned on the HBA, but after a reboot the disks connected to the controller are not displayed. Why?

root@hba:~/hpsahba# ./hpsahba -i /dev/sg0
VENDOR_ID='HP'
PRODUCT_ID='P212'
BOARD_ID='0x3241103c'
SOFTWARE_NAME=''
HARDWARE_NAME=''
RUNNING_FIRM_REV='6.64'
ROM_FIRM_REV='6.63'
REC_ROM_INACTIVE_REV='6.63'
YET_MORE_CONTROLLER_FLAGS='0xfa51a227'
NVRAM_FLAGS='0x08'
HBA_MODE_SUPPORTED=1
HBA_MODE_ENABLED=1

root@hba:~/hpsahba# lsblk
NAME                      MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0                       7:0    0  67.8M  1 loop /snap/lxd/22753
loop1                       7:1    0    47M  1 loop /snap/snapd/16292
loop2                       7:2    0    62M  1 loop /snap/core20/1611
loop3                       7:3    0  91.9M  1 loop /snap/lxd/24061
sda                         8:0    0 447.1G  0 disk
├─sda1                      8:1    0     1M  0 part
├─sda2                      8:2    0     2G  0 part /boot
└─sda3                      8:3    0 445.1G  0 part
  └─ubuntu--vg-ubuntu--lv 253:0    0   100G  0 lvm  /
sdb                         8:16   1 115.5G  0 disk
├─sdb1                      8:17   1    50M  0 part
├─sdb2                      8:18   1    50M  0 part
└─sdb3                      8:19   1 115.4G  0 part

**Comment by OMMJAI** [comment]
Hi, You have to use the command `sudo echo "options hpsa hpsa_use_nvram_hba_flag=1" > /etc/modprobe.d/hpsa.conf`
What this does is modifies hpsa.conf. So that you will have the disks on reboot.

**Comment by OMMJAI** [comment]
Could you explain how you used the dkms module on linux kernel 5.15. I am stuck on kernel 5.4 as the dkms' version number is limited to 5.8.
